; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.41"

; Modules
projects[ctools][version] = "1.9"

projects[colorbox][version] = "2.9"

projects[imagemagick][version] = "1.0"

projects[libraries][version] = "2.2"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.6"

projects[views][version] = "3.11"

projects[xmlsitemap][version] = "2.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora][download][type] = "git"
projects[islandora][download][url] = "git://github.com/Islandora/islandora.git"
projects[islandora][download][tag] = "7.x-1.6"
projects[islandora][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_audio][download][type] = "git"
projects[islandora_audio][download][url] = "git://github.com/Islandora/islandora_solution_pack_audio.git"
projects[islandora_audio][download][tag] = "7.x-1.6"
projects[islandora_audio][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_bagit][download][type] = "git"
projects[islandora_bagit][download][url] = "git://github.com/Islandora/islandora_bagit.git"
projects[islandora_bagit][download][tag] = "7.x-1.6"
projects[islandora_bagit][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_solution_pack_collection][download][type] = "git"
projects[islandora_solution_pack_collection][download][url] = "git://github.com/Islandora/islandora_solution_pack_collection.git"
projects[islandora_solution_pack_collection][download][tag] = "7.x-1.6"
projects[islandora_solution_pack_collection][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_basic_image][download][type] = "git"
projects[islandora_basic_image][download][url] = "git://github.com/Islandora/islandora_solution_pack_image.git"
projects[islandora_basic_image][download][tag] = "7.x-1.6"
projects[islandora_basic_image][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_batch][download][type] = "git"
projects[islandora_batch][download][url] = "git://github.com/Islandora/islandora_batch.git"
projects[islandora_batch][download][tag] = "7.x-1.6"
projects[islandora_batch][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_book][download][type] = "git"
projects[islandora_book][download][url] = "git://github.com/Islandora/islandora_solution_pack_book.git"
projects[islandora_book][download][tag] = "7.x-1.6"
projects[islandora_book][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_bookmark][download][type] = "git"
projects[islandora_bookmark][download][url] = "git://github.com/Islandora/islandora_bookmark.git"
projects[islandora_bookmark][download][tag] = "7.x-1.6"
projects[islandora_bookmark][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_checksum][download][type] = "git"
projects[islandora_checksum][download][url] = "git://github.com/Islandora/islandora_checksum.git"
projects[islandora_checksum][download][tag] = "7.x-1.6"
projects[islandora_checksum][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_checksum_checker][download][type] = "git"
projects[islandora_checksum_checker][download][url] = "git://github.com/Islandora/islandora_checksum_checker.git"
projects[islandora_checksum_checker][download][tag] = "7.x-1.6"
projects[islandora_checksum_checker][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_compound_object][download][type] = "git"
projects[islandora_compound_object][download][url] = "git://github.com/Islandora/islandora_solution_pack_compound.git"
projects[islandora_compound_object][download][tag] = "7.x-1.6"
projects[islandora_compound_object][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_disk_image][download][type] = "git"
projects[islandora_disk_image][download][url] = "git://github.com/Islandora/islandora_solution_pack_disk_image.git"
projects[islandora_disk_image][download][tag] = "7.x-1.6"
projects[islandora_disk_image][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_entities][download][type] = "git"
projects[islandora_entities][download][url] = "git://github.com/Islandora/islandora_solution_pack_entities.git"
projects[islandora_entities][download][tag] = "7.x-1.6"
projects[islandora_entities][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_fits][download][type] = "git"
projects[islandora_fits][download][url] = "git://github.com/Islandora/islandora_fits.git"
projects[islandora_fits][download][tag] = "7.x-1.6"
projects[islandora_fits][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
; Ask Kristian about this module - no 7.x-1.6 version available
projects[islandora_image_annotation][download][type] = "git"
projects[islandora_image_annotation][download][url] = "git://github.com/Islandora-Labs/islandora_image_annotation.git"
projects[islandora_image_annotation][download][tag] = "7.x-1.5"
projects[islandora_image_annotation][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_importer][download][type] = "git"
projects[islandora_importer][download][url] = "git://github.com/Islandora/islandora_importer.git"
projects[islandora_importer][download][tag] = "7.x-1.6"
projects[islandora_importer][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_internet_archive_bookreader][download][type] = "git"
projects[islandora_internet_archive_bookreader][download][url] = "git://github.com/Islandora/islandora_internet_archive_bookreader.git"
projects[islandora_internet_archive_bookreader][download][tag] = "7.x-1.6"
projects[islandora_internet_archive_bookreader][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_jwplayer][download][type] = "git"
projects[islandora_jwplayer][download][url] = "git://github.com/Islandora/islandora_jwplayer.git"
projects[islandora_jwplayer][download][tag] = "7.x-1.6"
projects[islandora_jwplayer][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_large_image][download][type] = "git"
projects[islandora_large_image][download][url] = "git://github.com/Islandora/islandora_solution_pack_large_image.git"
projects[islandora_large_image][download][tag] = "7.x-1.6"
projects[islandora_large_image][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_manuscript][download][type] = "git"
projects[islandora_manuscript][download][url] = "git://github.com/UCLALibrary/islandora_solution_pack_manuscript.git"
projects[islandora_manuscript][download][branch] = "7.x"
projects[islandora_manuscript][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_newspaper][download][type] = "git"
projects[islandora_newspaper][download][url] = "git://github.com/Islandora/islandora_solution_pack_newspaper.git"
projects[islandora_newspaper][download][tag] = "7.x-1.6"
projects[islandora_newspaper][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_oai][download][type] = "git"
projects[islandora_oai][download][url] = "git://github.com/Islandora/islandora_oai.git"
projects[islandora_oai][download][tag] = "7.x-1.6"
projects[islandora_oai][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_ocr][download][type] = "git"
projects[islandora_ocr][download][url] = "git://github.com/Islandora/islandora_ocr.git"
projects[islandora_ocr][download][tag] = "7.x-1.6"
projects[islandora_ocr][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_openseadragon][download][type] = "git"
projects[islandora_openseadragon][download][url] = "git://github.com/Islandora/islandora_openseadragon.git"
projects[islandora_openseadragon][download][tag] = "7.x-1.6"
projects[islandora_openseadragon][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_paged_content][download][type] = "git"
projects[islandora_paged_content][download][url] = "git://github.com/Islandora/islandora_paged_content.git"
projects[islandora_paged_content][download][tag] = "7.x-1.6"
projects[islandora_paged_content][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_pathauto][download][type] = "git"
projects[islandora_pathauto][download][url] = "git://github.com/Islandora/islandora_pathauto.git"
projects[islandora_pathauto][download][tag] = "7.x-1.6"
projects[islandora_pathauto][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_pdf][download][type] = "git"
projects[islandora_pdf][download][url] = "git://github.com/Islandora/islandora_solution_pack_pdf.git"
projects[islandora_pdf][download][tag] = "7.x-1.6"
projects[islandora_pdf][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_pdfjs][download][type] = "git"
projects[islandora_pdfjs][download][url] = "git://github.com/Islandora/islandora_pdfjs.git"
projects[islandora_pdfjs][download][tag] = "7.x-1.6"
projects[islandora_pdfjs][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_simple_workflow][download][type] = "git"
projects[islandora_simple_workflow][download][url] = "git://github.com/Islandora/islandora_simple_workflow.git"
projects[islandora_simple_workflow][download][tag] = "7.x-1.6"
projects[islandora_simple_workflow][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_solr][download][type] = "git"
projects[islandora_solr][download][url] = "git://github.com/Islandora/islandora_solr_search.git"
projects[islandora_solr][download][tag] = "7.x-1.6"
projects[islandora_solr][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_solr_facet_pages][download][type] = "git"
projects[islandora_solr_facet_pages][download][url] = "git://github.com/Islandora/islandora_solr_facet_pages.git"
projects[islandora_solr_facet_pages][download][tag] = "7.x-1.6"
projects[islandora_solr_facet_pages][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_solr_metadata][download][type] = "git"
projects[islandora_solr_metadata][download][url] = "git://github.com/Islandora/islandora_solr_metadata.git"
projects[islandora_solr_metadata][download][tag] = "7.x-1.6"
projects[islandora_solr_metadata][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_solr_views][download][type] = "git"
projects[islandora_solr_views][download][url] = "git://github.com/Islandora/islandora_solr_views.git"
projects[islandora_solr_views][download][tag] = "7.x-1.6"
projects[islandora_solr_views][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_video][download][type] = "git"
projects[islandora_video][download][url] = "git://github.com/Islandora/islandora_solution_pack_video.git"
projects[islandora_video][download][tag] = "7.x-1.6"
projects[islandora_video][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_videojs][download][type] = "git"
projects[islandora_videojs][download][url] = "git://github.com/Islandora/islandora_videojs.git"
projects[islandora_videojs][download][tag] = "7.x-1.6"
projects[islandora_videojs][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_web_archive][download][type] = "git"
projects[islandora_web_archive][download][url] = "git://github.com/Islandora/islandora_solution_pack_web_archive.git"
projects[islandora_web_archive][download][tag] = "7.x-1.6"
projects[islandora_web_archive][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_xacml_editor][download][type] = "git"
projects[islandora_xacml_editor][download][url] = "git://github.com/Islandora/islandora_xacml_editor.git"
projects[islandora_xacml_editor][download][tag] = "7.x-1.6"
projects[islandora_xacml_editor][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[islandora_xmlsitemap][download][type] = "git"
projects[islandora_xmlsitemap][download][url] = "git://github.com/Islandora/islandora_xmlsitemap.git"
projects[islandora_xmlsitemap][download][tag] = "7.x-1.6"
projects[islandora_xmlsitemap][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[objective_forms][download][type] = "git"
projects[objective_forms][download][url] = "git://github.com/Islandora/objective_forms.git"
projects[objective_forms][download][tag] = "7.x-1.6"
projects[objective_forms][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[php_lib][download][type] = "git"
projects[php_lib][download][url] = "git://github.com/Islandora/php_lib.git"
projects[php_lib][download][tag] = "7.x-1.6"
projects[php_lib][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[xml_forms][download][type] = "git"
projects[xml_forms][download][url] = "git://github.com/Islandora/islandora_xml_forms.git"
projects[xml_forms][download][tag] = "7.x-1.6"
projects[xml_forms][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[pdfjs][download][type] = "git"
libraries[pdfjs][download][url] = "git://github.com/mozilla/pdf.js.git"
libraries[pdfjs][download][tag] = "v1.1.469"
libraries[pdfjs][directory_name] = "pdfjs"
libraries[pdfjs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jstree][download][type] = "git"
libraries[jstree][download][url] = "git://github.com/vakata/jstree.git"
libraries[jstree][download][tag] = "3.2.1"
libraries[jstree][directory_name] = "jstree"
libraries[jstree][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[bookreader][download][type] = "git"
libraries[bookreader][download][url] = "git://github.com/Islandora/internet_archive_bookreader.git"
libraries[bookreader][download][tag] = "Release29"
libraries[bookreader][directory_name] = "bookreader"
libraries[bookreader][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jwplayer][download][type] = "file"
libraries[jwplayer][download][url] = "https://account.jwplayer.com/static/download/jwplayer-6.12.zip"
libraries[jwplayer][download][md5] = "fc733ca3f88a15c59c340a769da496ab"
libraries[jwplayer][directory_name] = "jwplayer"
libraries[jwplayer][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "git://github.com/jackmoore/colorbox.git"
libraries[colorbox][download][tag] = "1.6.3"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[BagItPHP][download][type] = "git"
libraries[BagItPHP][download][url] = "git://github.com/scholarslab/BagItPHP.git"
libraries[BagItPHP][download][tag] = "0.3.0"
libraries[BagItPHP][directory_name] = "BagItPHP"
libraries[BagItPHP][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tuque][download][type] = "git"
libraries[tuque][download][url] = "git://github.com/Islandora/tuque.git"
libraries[tuque][download][tag] = "1.6"
libraries[tuque][directory_name] = "tuque"
libraries[tuque][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[JAIL][download][type] = "git"
libraries[JAIL][download][url] = "git://github.com/sebarmeli/JAIL.git"
libraries[JAIL][download][branch] = "master"
libraries[JAIL][directory_name] = "JAIL"
libraries[JAIL][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[openseadragon][download][type] = "git"
libraries[openseadragon][download][url] = "git://github.com/openseadragon/openseadragon.git"
libraries[openseadragon][download][tag] = "v0.9.129"
libraries[openseadragon][directory_name] = "openseadragon"
libraries[openseadragon][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[video-js][download][type] = "git"
libraries[video-js][download][url] = "git://github.com/videojs/video.js.git"
libraries[video-js][download][tag] = "v5.2.4"
libraries[video-js][directory_name] = "video-js"
libraries[video-js][type] = "library"

